import fs from "fs";
import path from "path";

const targetDir = path.join(process.cwd(), "public", "dishes");

// 63 dishes comprehensive definition
const catalog = [
  // ================= 1. YÖRESEL BAŞYAPITLAR (21 Ürün) =================
  {
    id: "kol-dolmasi-2-kisilik",
    category: "Yöresel Başyapıtlar",
    categorySlug: "yoresel",
    name: "Kol Dolması (2 Kişilik)",
    subtitle: "12 Saat Kısık Ateşte • Bademli İç Pilav • Bakır Sahan",
    price: "₺ 1.300",
    priceNum: 1300,
    image: "/dishes/sur-kuzu-kol-dolmasi.png",
    dishImage: "/dishes/sur-kuzu-kol-dolmasi.png",
    description: "12 saat kısık ateşte demlenen bütün kuzu kol dolması, bademli iç pilav ile bakır sahanda.",
    chefNote: "12 saat kısık ateşte demlenen bütün kuzu kol dolması, bademli iç pilav ile bakır sahanda.",
    calories: "1450 kcal",
    prepTime: "35 dk",
    servingTemp: "75°C",
    temperature: "75°C",
    portion: "650g / 2 Kişilik",
    allergens: "Kuruyemiş (Badem)"
  },
  {
    id: "asci-tabagi",
    category: "Yöresel Başyapıtlar",
    categorySlug: "yoresel",
    name: "Aşçı Tabağı",
    subtitle: "Tandır • İncik • Kol Dolması • Pirinç Pilavı",
    price: "₺ 985",
    priceNum: 985,
    image: "/dishes/asci-tabagi.png",
    dishImage: "/dishes/asci-tabagi.png",
    description: "Tandır, kuzu incik, kol dolması ve pilavdan oluşan zengin konak seçkisi.",
    chefNote: "Tandır, kuzu incik, kol dolması ve pilavdan oluşan zengin konak seçkisi.",
    calories: "1150 kcal",
    prepTime: "20 dk",
    servingTemp: "74°C",
    temperature: "74°C",
    portion: "500g",
    allergens: "Gluten"
  },
  {
    id: "keci-kavurmasi",
    category: "Yöresel Başyapıtlar",
    categorySlug: "yoresel",
    name: "Keçi Kavurması",
    subtitle: "Taş Fırında Ağır Pişirim • Karacadağ Keçi Eti",
    price: "₺ 720",
    priceNum: 720,
    image: "/dishes/keci-kavurmasi.png",
    dishImage: "/dishes/keci-kavurmasi.png",
    description: "Taş fırında ağır ateşte pişen yöresel keçi kavurması.",
    chefNote: "Taş fırında ağır ateşte pişen yöresel keçi kavurması.",
    calories: "650 kcal",
    prepTime: "20 dk",
    servingTemp: "76°C",
    temperature: "76°C",
    portion: "300g",
    allergens: "Doğal Et (Alerjensiz)"
  },
  {
    id: "pilav-ustu-kol-dolmasi",
    category: "Yöresel Başyapıtlar",
    categorySlug: "yoresel",
    name: "Pilav Üstü Kuzu Kol Dolması",
    subtitle: "Bademli İç Pilav • Lif Lif Ayrılan Kuzu Kol",
    price: "₺ 690",
    priceNum: 690,
    image: "/dishes/pilav-ustu-kol-dolmasi.png",
    dishImage: "/dishes/pilav-ustu-kol-dolmasi.png",
    description: "Bademli iç pilav üzerinde servis edilen kuzu kol eti.",
    chefNote: "Bademli iç pilav üzerinde servis edilen kuzu kol eti.",
    calories: "820 kcal",
    prepTime: "15 dk",
    servingTemp: "74°C",
    temperature: "74°C",
    portion: "350g",
    allergens: "Kuruyemiş (Badem), Gluten"
  },
  {
    id: "pilav-ustu-tandir",
    category: "Yöresel Başyapıtlar",
    categorySlug: "yoresel",
    name: "Pilav Üstü Tandır",
    subtitle: "Taş Fırında Pişen Kuzu Tandır • Tane Pilav",
    price: "₺ 685",
    priceNum: 685,
    image: "/dishes/pilav-ustu-tandir.png",
    dishImage: "/dishes/pilav-ustu-tandir.png",
    description: "Taş fırında pişen kuzu tandır eti, tane pirinç pilavı ile.",
    chefNote: "Taş fırında pişen kuzu tandır eti, tane pirinç pilavı ile.",
    calories: "780 kcal",
    prepTime: "15 dk",
    servingTemp: "74°C",
    temperature: "74°C",
    portion: "340g",
    allergens: "Gluten"
  },
  {
    id: "firinda-kuzu-incik",
    category: "Yöresel Başyapıtlar",
    categorySlug: "yoresel",
    name: "Fırında Kuzu İncik",
    subtitle: "Fırınlanmış Kök Sebzeler • İlikli Et Sosu",
    price: "₺ 680",
    priceNum: 680,
    image: "/dishes/firinda-kuzu-incik.png",
    dishImage: "/dishes/firinda-kuzu-incik.png",
    description: "Fırınlanmış kök sebzeler ve ilikli et sosu ile ağır pişirim.",
    chefNote: "Fırınlanmış kök sebzeler ve ilikli et sosu ile ağır pişirim.",
    calories: "710 kcal",
    prepTime: "20 dk",
    servingTemp: "75°C",
    temperature: "75°C",
    portion: "400g",
    allergens: "Alerjensiz"
  },
  {
    id: "firin-agzi",
    category: "Yöresel Başyapıtlar",
    categorySlug: "yoresel",
    name: "Fırın Ağzı",
    subtitle: "Sarımsak & Köz Biberle Tepside Kızartılan Diyarbakır Klasiği",
    price: "₺ 680",
    priceNum: 680,
    image: "/dishes/firin-guvec.png",
    dishImage: "/dishes/firin-guvec.png",
    description: "Kuzu eti, sarımsak ve biberle tepside nar gibi kızartılan Diyarbakır klasiği.",
    chefNote: "Kuzu eti, sarımsak ve biberle tepside nar gibi kızartılan Diyarbakır klasiği.",
    calories: "740 kcal",
    prepTime: "25 dk",
    servingTemp: "78°C",
    temperature: "78°C",
    portion: "350g",
    allergens: "Alerjensiz"
  },
  {
    id: "patlican-yataginda-incik",
    category: "Yöresel Başyapıtlar",
    categorySlug: "yoresel",
    name: "Patlıcan Yatağında Kuzu İncik",
    subtitle: "Közlenmiş Beğendi • Yumuşacık Kuzu İncik",
    price: "₺ 670",
    priceNum: 670,
    image: "/dishes/firinda-kuzu-incik.png",
    dishImage: "/dishes/firinda-kuzu-incik.png",
    description: "Közlenmiş patlıcan beğendi üzerinde yumuşacık kuzu incik.",
    chefNote: "Közlenmiş patlıcan beğendi üzerinde yumuşacık kuzu incik.",
    calories: "680 kcal",
    prepTime: "20 dk",
    servingTemp: "74°C",
    temperature: "74°C",
    portion: "380g",
    allergens: "Laktoz (Süt/Tereyağı)"
  },
  {
    id: "firinda-gerdan",
    category: "Yöresel Başyapıtlar",
    categorySlug: "yoresel",
    name: "Fırında Gerdan",
    subtitle: "Kemik Suyunda Lif Lif Ayrılan Kuzu Gerdan",
    price: "₺ 670",
    priceNum: 670,
    image: "/dishes/kuzu-gerdan.png",
    dishImage: "/dishes/kuzu-gerdan.png",
    description: "Kemik suyunda lif lif ayrılan kuzu gerdan eti.",
    chefNote: "Kemik suyunda lif lif ayrılan kuzu gerdan eti.",
    calories: "670 kcal",
    prepTime: "18 dk",
    servingTemp: "75°C",
    temperature: "75°C",
    portion: "350g",
    allergens: "Alerjensiz"
  },
  {
    id: "kuzu-gerdan",
    category: "Yöresel Başyapıtlar",
    categorySlug: "yoresel",
    name: "Kuzu Gerdan",
    subtitle: "Döküm Tavada Köz Biber & Domates",
    price: "₺ 670",
    priceNum: 670,
    image: "/dishes/kuzu-gerdan.png",
    dishImage: "/dishes/kuzu-gerdan.png",
    description: "Döküm tavada köz biber ve domates eşliğinde geleneksel gerdan.",
    chefNote: "Döküm tavada köz biber ve domates eşliğinde geleneksel gerdan.",
    calories: "640 kcal",
    prepTime: "15 dk",
    servingTemp: "74°C",
    temperature: "74°C",
    portion: "330g",
    allergens: "Alerjensiz"
  },
  {
    id: "kuzu-haslama",
    category: "Yöresel Başyapıtlar",
    categorySlug: "yoresel",
    name: "Kuzu Haşlama",
    subtitle: "Şifalı İlikli Et Suyu • Taze Patates & Havuç",
    price: "₺ 670",
    priceNum: 670,
    image: "/dishes/kuzu-haslama.png",
    dishImage: "/dishes/kuzu-haslama.png",
    description: "Şifalı ilikli et suyu, taze patates ve havuç ile haşlama.",
    chefNote: "Şifalı ilikli et suyu, taze patates ve havuç ile haşlama.",
    calories: "580 kcal",
    prepTime: "15 dk",
    servingTemp: "78°C",
    temperature: "78°C",
    portion: "360g",
    allergens: "Alerjensiz"
  },
  {
    id: "kekikli-kuzu-budu",
    category: "Yöresel Başyapıtlar",
    categorySlug: "yoresel",
    name: "Kekikli Kuzu Budu",
    subtitle: "Dağ Kekiği Aromalı • Fırınlanmış Kuzu Budu",
    price: "₺ 670",
    priceNum: 670,
    image: "/dishes/special-kuzu-sirt.png",
    dishImage: "/dishes/special-kuzu-sirt.png",
    description: "Dağ kekiği aromalı fırınlanmış kuzu budu.",
    chefNote: "Dağ kekiği aromalı fırınlanmış kuzu budu.",
    calories: "670 kcal",
    prepTime: "20 dk",
    servingTemp: "75°C",
    temperature: "75°C",
    portion: "350g",
    allergens: "Alerjensiz"
  },
  {
    id: "kuzu-graten",
    category: "Yöresel Başyapıtlar",
    categorySlug: "yoresel",
    name: "Kuzu Graten",
    subtitle: "Fırınlanmış Kaşar Kabuklu Kuzu Eti Dilimleri",
    price: "₺ 680",
    priceNum: 680,
    image: "/dishes/special-kuzu-sirt.png",
    dishImage: "/dishes/special-kuzu-sirt.png",
    description: "Fırınlanmış kaşar kabuklu kuzu eti dilimleri.",
    chefNote: "Fırınlanmış kaşar kabuklu kuzu eti dilimleri.",
    calories: "730 kcal",
    prepTime: "20 dk",
    servingTemp: "76°C",
    temperature: "76°C",
    portion: "320g",
    allergens: "Laktoz"
  },
  {
    id: "diyarbakir-kavurma",
    category: "Yöresel Başyapıtlar",
    categorySlug: "yoresel",
    name: "Diyarbakır Kavurma",
    subtitle: "Kendi Yağında Meşe Közünde Demleme",
    price: "₺ 660",
    priceNum: 660,
    image: "/dishes/ayvali-kavurma.png",
    dishImage: "/dishes/ayvali-kavurma.png",
    description: "Kendi yağında meşe közünde demlenen geleneksel kavurma.",
    chefNote: "Kendi yağında meşe közünde demlenen geleneksel kavurma.",
    calories: "690 kcal",
    prepTime: "15 dk",
    servingTemp: "76°C",
    temperature: "76°C",
    portion: "300g",
    allergens: "Alerjensiz"
  },
  {
    id: "sade-tandir",
    category: "Yöresel Başyapıtlar",
    categorySlug: "yoresel",
    name: "Sade Tandır",
    subtitle: "Kuyuda Pişmiş Tandır Eti • Tırnak Pide",
    price: "₺ 560",
    priceNum: 560,
    image: "/dishes/sade-tandir.png",
    dishImage: "/dishes/sade-tandir.png",
    description: "Kuyuda pişmiş tandır eti, tırnak pide ile.",
    chefNote: "Kuyuda pişmiş tandır eti, tırnak pide ile.",
    calories: "620 kcal",
    prepTime: "15 dk",
    servingTemp: "74°C",
    temperature: "74°C",
    portion: "280g",
    allergens: "Gluten (Pide)"
  },
  {
    id: "firin-guvec",
    category: "Yöresel Başyapıtlar",
    categorySlug: "yoresel",
    name: "Fırın Güveç",
    subtitle: "Toprak Güveçte Kuzu Kuşbaşı • Mevsim Sebzeleri",
    price: "₺ 480",
    priceNum: 480,
    image: "/dishes/firin-guvec.png",
    dishImage: "/dishes/firin-guvec.png",
    description: "Toprak güveçte kuzu kuşbaşı, domates ve patlıcan uyumu.",
    chefNote: "Toprak güveçte kuzu kuşbaşı, domates ve patlıcan uyumu.",
    calories: "520 kcal",
    prepTime: "20 dk",
    servingTemp: "78°C",
    temperature: "78°C",
    portion: "350g",
    allergens: "Alerjensiz"
  },
  {
    id: "eksili-kofte",
    category: "Yöresel Başyapıtlar",
    categorySlug: "yoresel",
    name: "Ekşili Köfte",
    subtitle: "Sumaklı Yöresel Sos • Konak Köftesi",
    price: "₺ 480",
    priceNum: 480,
    image: "/dishes/eksili-kofte.png",
    dishImage: "/dishes/eksili-kofte.png",
    description: "Sumaklı yöresel sos eşliğinde konak köftesi.",
    chefNote: "Sumaklı yöresel sos eşliğinde konak köftesi.",
    calories: "510 kcal",
    prepTime: "18 dk",
    servingTemp: "75°C",
    temperature: "75°C",
    portion: "320g",
    allergens: "Gluten"
  },
  {
    id: "etsiz-sebze-yemegi",
    category: "Yöresel Başyapıtlar",
    categorySlug: "yoresel",
    name: "Etsiz Sebze Yemeği",
    subtitle: "Mevsim Sebzeleriyle Hazırlanan Hafif Güveç",
    price: "₺ 475",
    priceNum: 475,
    image: "/dishes/sebze-yemegi.png",
    dishImage: "/dishes/sebze-yemegi.png",
    description: "Mevsim sebzeleriyle hazırlanan hafif güveç.",
    chefNote: "Mevsim sebzeleriyle hazırlanan hafif güveç.",
    calories: "310 kcal",
    prepTime: "15 dk",
    servingTemp: "72°C",
    temperature: "72°C",
    portion: "300g",
    allergens: "Alerjensiz"
  },
  {
    id: "az-kavurma",
    category: "Yöresel Başyapıtlar",
    categorySlug: "yoresel",
    name: "Az Kavurma",
    subtitle: "Tek Kişilik Hafif Porsiyon Diyarbakır Kavurması",
    price: "₺ 410",
    priceNum: 410,
    image: "/dishes/az-kavurma.png",
    dishImage: "/dishes/az-kavurma.png",
    description: "Tek kişilik porsiyon Diyarbakır kavurması.",
    chefNote: "Tek kişilik porsiyon Diyarbakır kavurması.",
    calories: "420 kcal",
    prepTime: "10 dk",
    servingTemp: "75°C",
    temperature: "75°C",
    portion: "180g",
    allergens: "Alerjensiz"
  },
  {
    id: "az-tandir",
    category: "Yöresel Başyapıtlar",
    categorySlug: "yoresel",
    name: "Az Tandır",
    subtitle: "Tek Kişilik Kuyu Tandır Porsiyonu",
    price: "₺ 410",
    priceNum: 410,
    image: "/dishes/az-tandir.png",
    dishImage: "/dishes/az-tandir.png",
    description: "Tek kişilik kuyu tandır porsiyonu, lavaş ile.",
    chefNote: "Tek kişilik kuyu tandır porsiyonu, lavaş ile.",
    calories: "390 kcal",
    prepTime: "10 dk",
    servingTemp: "74°C",
    temperature: "74°C",
    portion: "180g",
    allergens: "Gluten"
  },
  {
    id: "az-guvec",
    category: "Yöresel Başyapıtlar",
    categorySlug: "yoresel",
    name: "Az Güveç",
    subtitle: "Tek Kişilik Hafif Toprak Güveç",
    price: "₺ 300",
    priceNum: 300,
    image: "/dishes/az-guvec.png",
    dishImage: "/dishes/az-guvec.png",
    description: "Geleneksel güveç, tek kişilik hafif porsiyon.",
    chefNote: "Geleneksel güveç, tek kişilik hafif porsiyon.",
    calories: "340 kcal",
    prepTime: "12 dk",
    servingTemp: "76°C",
    temperature: "76°C",
    portion: "200g",
    allergens: "Alerjensiz"
  },

  // ================= 2. SPECİALLER & ET IZGARA (11 Ürün) =================
  {
    id: "special-kuzu-sirt",
    category: "Specialler & Izgara",
    categorySlug: "tas-firin",
    name: "Beroş Special Kuzu Sırt",
    subtitle: "Özel Marine Kuzu Sırt • Firik Pilavı • Dağ Kekiği",
    price: "₺ 850",
    priceNum: 850,
    image: "/dishes/special-kuzu-sirt.png",
    dishImage: "/dishes/special-kuzu-sirt.png",
    description: "Marine kuzu sırt eti meşe odununda dinlendirilerek pişirilir.",
    chefNote: "Marine kuzu sırt eti meşe odununda dinlendirilerek pişirilir.",
    calories: "740 kcal",
    prepTime: "25 dk",
    servingTemp: "75°C",
    temperature: "75°C",
    portion: "350g",
    allergens: "Alerjensiz"
  },
  {
    id: "beros-acili-bonfile",
    category: "Specialler & Izgara",
    categorySlug: "tas-firin",
    name: "Beroş Usulü Acılı Bonfile",
    subtitle: "Özel Acı Biber Glazesi • Dana Bonfile Dilimleri",
    price: "₺ 910",
    priceNum: 910,
    image: "/dishes/special-kuzu-sirt.png",
    dishImage: "/dishes/special-kuzu-sirt.png",
    description: "Özel acı sos ve taze baharatlarla dinlendirilmiş ızgara dana bonfile.",
    chefNote: "Özel acı sos ve taze baharatlarla dinlendirilmiş ızgara dana bonfile.",
    calories: "680 kcal",
    prepTime: "20 dk",
    servingTemp: "74°C",
    temperature: "74°C",
    portion: "300g",
    allergens: "Alerjensiz"
  },
  {
    id: "beros-loqum-bonfile",
    category: "Specialler & Izgara",
    categorySlug: "tas-firin",
    name: "Beroş Usulü Loqum Bonfile",
    subtitle: "Tereyağında Mühürlenmiş Pamuk Bonfile",
    price: "₺ 920",
    priceNum: 920,
    image: "/dishes/special-kuzu-sirt.png",
    dishImage: "/dishes/special-kuzu-sirt.png",
    description: "Ağızda dağılan yumuşaklıkta mühürlenmiş dana bonfile lokumları.",
    chefNote: "Ağızda dağılan yumuşaklıkta mühürlenmiş dana bonfile lokumları.",
    calories: "720 kcal",
    prepTime: "18 dk",
    servingTemp: "75°C",
    temperature: "75°C",
    portion: "300g",
    allergens: "Laktoz (Tereyağı)"
  },
  {
    id: "loqum-bonfile",
    category: "Specialler & Izgara",
    categorySlug: "tas-firin",
    name: "Loqum Bonfile",
    subtitle: "Izgara Kuşkonmaz & Fırın Patates Eşliğinde",
    price: "₺ 900",
    priceNum: 900,
    image: "/dishes/special-kuzu-sirt.png",
    dishImage: "/dishes/special-kuzu-sirt.png",
    description: "Kömür ateşinde ızgara edilmiş marine bonfile dilimleri.",
    chefNote: "Kömür ateşinde ızgara edilmiş marine bonfile dilimleri.",
    calories: "650 kcal",
    prepTime: "18 dk",
    servingTemp: "74°C",
    temperature: "74°C",
    portion: "280g",
    allergens: "Alerjensiz"
  },
  {
    id: "patates-yataginda-bonfile",
    category: "Specialler & Izgara",
    categorySlug: "tas-firin",
    name: "Patates Yatağında Bonfile",
    subtitle: "Kıtır Kibrit Patates • Yoğurtlu Sos",
    price: "₺ 910",
    priceNum: 910,
    image: "/dishes/special-kuzu-sirt.png",
    dishImage: "/dishes/special-kuzu-sirt.png",
    description: "İnce çıtır patates yatağında servis edilen bonfile şeritleri.",
    chefNote: "İnce çıtır patates yatağında servis edilen bonfile şeritleri.",
    calories: "760 kcal",
    prepTime: "20 dk",
    servingTemp: "74°C",
    temperature: "74°C",
    portion: "350g",
    allergens: "Laktoz"
  },
  {
    id: "beros-special-1",
    category: "Specialler & Izgara",
    categorySlug: "tas-firin",
    name: "Beroş Special 1",
    subtitle: "Özel Fırınlama Et Karışımı • Konak Sosu",
    price: "₺ 845",
    priceNum: 845,
    image: "/dishes/karisik-izgara.png",
    dishImage: "/dishes/karisik-izgara.png",
    description: "Şefin özel kuzu ve dana eti harmonisi, köz garnitür ile.",
    chefNote: "Şefin özel kuzu ve dana eti harmonisi, köz garnitür ile.",
    calories: "810 kcal",
    prepTime: "22 dk",
    servingTemp: "75°C",
    temperature: "75°C",
    portion: "400g",
    allergens: "Alerjensiz"
  },
  {
    id: "ozel-siparis-kaburga",
    category: "Specialler & Izgara",
    categorySlug: "tas-firin",
    name: "Özel Sipariş Kaburga",
    subtitle: "Bütün Kuzu Kaburga • Odun Fırınında 8 Saat",
    price: "₺ 1.650",
    priceNum: 1650,
    image: "/dishes/sur-kuzu-kol-dolmasi.png",
    dishImage: "/dishes/sur-kuzu-kol-dolmasi.png",
    description: "Taş fırında nar gibi kızaran bütün kuzu kaburga ziyafeti.",
    chefNote: "Taş fırında nar gibi kızaran bütün kuzu kaburga ziyafeti.",
    calories: "1600 kcal",
    prepTime: "40 dk",
    servingTemp: "76°C",
    temperature: "76°C",
    portion: "800g / 2-3 Kişilik",
    allergens: "Alerjensiz"
  },
  {
    id: "cokertme",
    category: "Specialler & Izgara",
    categorySlug: "tas-firin",
    name: "Çökertme Kebabı",
    subtitle: "Kibrit Patates • Sarımsaklı Yoğurt • Domates Sos",
    price: "₺ 845",
    priceNum: 845,
    image: "/dishes/special-kuzu-sirt.png",
    dishImage: "/dishes/special-kuzu-sirt.png",
    description: "Çıtır patates üzerine dana eti dilimleri ve köy tereyağı.",
    chefNote: "Çıtır patates üzerine dana eti dilimleri ve köy tereyağı.",
    calories: "790 kcal",
    prepTime: "20 dk",
    servingTemp: "75°C",
    temperature: "75°C",
    portion: "380g",
    allergens: "Laktoz, Gluten"
  },
  {
    id: "kabak-meftune",
    category: "Specialler & Izgara",
    categorySlug: "tas-firin",
    name: "Diyarbakır Kabak Meftune",
    subtitle: "Sumak Suyu • Kuzu Eti • Taze Kabak Dilimleri",
    price: "₺ 480",
    priceNum: 480,
    image: "/dishes/firin-guvec.png",
    dishImage: "/dishes/firin-guvec.png",
    description: "Ekşi sumak suyuyla pişirilen asırlık Diyarbakır kabak yemeği.",
    chefNote: "Ekşi sumak suyuyla pişirilen asırlık Diyarbakır kabak yemeği.",
    calories: "510 kcal",
    prepTime: "20 dk",
    servingTemp: "74°C",
    temperature: "74°C",
    portion: "320g",
    allergens: "Alerjensiz"
  },
  {
    id: "kremali-loqum-bonfile",
    category: "Specialler & Izgara",
    categorySlug: "tas-firin",
    name: "Kremalı Loqum Bonfile",
    subtitle: "Taze Dağ Mantarlı Krema Sosu • Dana Bonfile",
    price: "₺ 925",
    priceNum: 925,
    image: "/dishes/special-kuzu-sirt.png",
    dishImage: "/dishes/special-kuzu-sirt.png",
    description: "Özel mantar kreması ile harmanlanan mühürlü dana lokum bonfile.",
    chefNote: "Özel mantar kreması ile harmanlanan mühürlü dana lokum bonfile.",
    calories: "820 kcal",
    prepTime: "20 dk",
    servingTemp: "75°C",
    temperature: "75°C",
    portion: "320g",
    allergens: "Laktoz (Krema)"
  },
  {
    id: "beef-stragonof",
    category: "Specialler & Izgara",
    categorySlug: "tas-firin",
    name: "Beef Stroganoff",
    subtitle: "Kornişon Turşu • Mantarlı Demiglace Sos • Jülyen Bonfile",
    price: "₺ 820",
    priceNum: 820,
    image: "/dishes/special-kuzu-sirt.png",
    dishImage: "/dishes/special-kuzu-sirt.png",
    description: "Jülyen doğranmış dana eti, mantar ve ekşi kremalı sos ile.",
    chefNote: "Jülyen doğranmış dana eti, mantar ve ekşi kremalı sos ile.",
    calories: "740 kcal",
    prepTime: "20 dk",
    servingTemp: "74°C",
    temperature: "74°C",
    portion: "330g",
    allergens: "Laktoz, Gluten"
  },

  // ================= 3. TAŞ FIRIN, PİDE & SAC TAVA (7 Ürün) =================
  {
    id: "sur-usulu-sac-tava",
    category: "Taş Fırın & Sac Tava",
    categorySlug: "tas-firin",
    name: "Sur Usulü Saç Tava",
    subtitle: "Kuzu Kuşbaşı • Köy Biberi • Domates • Kuyruk Yağı",
    price: "₺ 800",
    priceNum: 800,
    image: "/dishes/sur-usulu-sac-tava.png",
    dishImage: "/dishes/sur-usulu-sac-tava.png",
    description: "Özel dövme saç tavada yüksek ateşte cızırdayan taze kuzu eti.",
    chefNote: "Özel dövme saç tavada yüksek ateşte cızırdayan taze kuzu eti.",
    calories: "680 kcal",
    prepTime: "16 dk",
    servingTemp: "82°C",
    temperature: "82°C",
    portion: "350g",
    allergens: "Alerjensiz"
  },
  {
    id: "kusbasi-kasarli-pide",
    category: "Taş Fırın & Sac Tava",
    categorySlug: "tas-firin",
    name: "Kuşbaşı Kaşarlı Pide",
    subtitle: "Zırh Eti • Göbek Kaşar • Meşe Odunu Fırını",
    price: "₺ 595",
    priceNum: 595,
    image: "/dishes/kusbasi-kasarli-pide.png",
    dishImage: "/dishes/kusbasi-kasarli-pide.png",
    description: "Taş tabanlı fırında çıtır çıtır pişen bol malzemeli pide.",
    chefNote: "Taş tabanlı fırında çıtır çıtır pişen bol malzemeli pide.",
    calories: "890 kcal",
    prepTime: "12 dk",
    servingTemp: "85°C",
    temperature: "85°C",
    portion: "1 Porsiyon",
    allergens: "Gluten, Laktoz"
  },
  {
    id: "kusbasi-pide",
    category: "Taş Fırın & Sac Tava",
    categorySlug: "tas-firin",
    name: "Kuşbaşı Pide",
    subtitle: "Marine Kuşbaşı Kuzu Eti • Domates & Biber",
    price: "₺ 570",
    priceNum: 570,
    image: "/dishes/kusbasi-kasarli-pide.png",
    dishImage: "/dishes/kusbasi-kasarli-pide.png",
    description: "Geleneksel hamur ve marine kuşbaşı etin taş fırın buluşması.",
    chefNote: "Geleneksel hamur ve marine kuşbaşı etin taş fırın buluşması.",
    calories: "780 kcal",
    prepTime: "12 dk",
    servingTemp: "85°C",
    temperature: "85°C",
    portion: "1 Porsiyon",
    allergens: "Gluten"
  },
  {
    id: "kiymali-yumurtali-pide",
    category: "Taş Fırın & Sac Tava",
    categorySlug: "tas-firin",
    name: "Kıymalı Yumurtalı Pide",
    subtitle: "Köy Yumurtası • Baharatlı Dana Kıyma",
    price: "₺ 535",
    priceNum: 535,
    image: "/dishes/kusbasi-kasarli-pide.png",
    dishImage: "/dishes/kusbasi-kasarli-pide.png",
    description: "Fırından çıkmadan hemen önce kırılan sarısı akışkan köy yumurtalı pide.",
    chefNote: "Fırından çıkmadan hemen önce kırılan sarısı akışkan köy yumurtalı pide.",
    calories: "820 kcal",
    prepTime: "12 dk",
    servingTemp: "85°C",
    temperature: "85°C",
    portion: "1 Porsiyon",
    allergens: "Gluten, Yumurta"
  },
  {
    id: "lahmacun",
    category: "Taş Fırın & Sac Tava",
    categorySlug: "tas-firin",
    name: "Taş Fırın Lahmacun",
    subtitle: "Diyarbakır Usulü İnce Hamur • Zırh Kuzu Kıyma",
    price: "₺ 130",
    priceNum: 130,
    image: "/dishes/lahmacun.png",
    dishImage: "/dishes/lahmacun.png",
    description: "Taş fırında gevrek pişen, zırh kıyması ve isotlu gerçek lahmacun.",
    chefNote: "Taş fırında gevrek pişen, zırh kıyması ve isotlu gerçek lahmacun.",
    calories: "280 kcal",
    prepTime: "8 dk",
    servingTemp: "85°C",
    temperature: "85°C",
    portion: "1 Adet",
    allergens: "Gluten"
  },
  {
    id: "findik-lahmacun",
    category: "Taş Fırın & Sac Tava",
    categorySlug: "tas-firin",
    name: "Fındık Lahmacun",
    subtitle: "Atıştırmalık Mini Taş Fırın Lahmacun",
    price: "₺ 85",
    priceNum: 85,
    image: "/dishes/lahmacun.png",
    dishImage: "/dishes/lahmacun.png",
    description: "Tek lokmalık çıtır fındık lahmacun lezzeti.",
    chefNote: "Tek lokmalık çıtır fındık lahmacun lezzeti.",
    calories: "140 kcal",
    prepTime: "6 dk",
    servingTemp: "85°C",
    temperature: "85°C",
    portion: "1 Adet",
    allergens: "Gluten"
  },
  {
    id: "kasarli-pide",
    category: "Taş Fırın & Sac Tava",
    categorySlug: "tas-firin",
    name: "Kaşarlı Pide",
    subtitle: "Eriyen Bol Köy Kaşarı • Tereyağlı Çıtır Kenar",
    price: "₺ 560",
    priceNum: 560,
    image: "/dishes/kusbasi-kasarli-pide.png",
    dishImage: "/dishes/kusbasi-kasarli-pide.png",
    description: "Altın sarısı erimiş nefis kaşar peynirli fırın pidesi.",
    chefNote: "Altın sarısı erimiş nefis kaşar peynirli fırın pidesi.",
    calories: "790 kcal",
    prepTime: "12 dk",
    servingTemp: "85°C",
    temperature: "85°C",
    portion: "1 Porsiyon",
    allergens: "Gluten, Laktoz"
  },

  // ================= 4. TAVUK ÇEŞİTLERİ (5 Ürün) =================
  {
    id: "tavuk-sac-tava",
    category: "Tavuk Çeşitleri",
    categorySlug: "tavuk",
    name: "Beroş Tavuk Special (Saç Tava)",
    subtitle: "Körpe Tavuk But • Köy Biberi • Özel Baharat Harmanı",
    price: "₺ 590",
    priceNum: 590,
    image: "/dishes/tavuk-sac-tava.png",
    dishImage: "/dishes/tavuk-sac-tava.png",
    description: "Kızgın saçta taze biber ve domatesle sotelenmiş nefis tavuk eti.",
    chefNote: "Kızgın saçta taze biber ve domatesle sotelenmiş nefis tavuk eti.",
    calories: "510 kcal",
    prepTime: "14 dk",
    servingTemp: "80°C",
    temperature: "80°C",
    portion: "320g",
    allergens: "Alerjensiz"
  },
  {
    id: "korili-tavuk",
    category: "Tavuk Çeşitleri",
    categorySlug: "tavuk",
    name: "Köri Soslu Tavuk",
    subtitle: "Özel Harman Hint Köri Sosu • Taze Krema • Mantar",
    price: "₺ 550",
    priceNum: 550,
    image: "/dishes/korili-tavuk.png",
    dishImage: "/dishes/korili-tavuk.png",
    description: "Yumuşak tavuk göğsü dilimleri zengin köri aromalı kremayla harmanlanır.",
    chefNote: "Yumuşak tavuk göğsü dilimleri zengin köri aromalı kremayla harmanlanır.",
    calories: "530 kcal",
    prepTime: "15 dk",
    servingTemp: "75°C",
    temperature: "75°C",
    portion: "320g",
    allergens: "Laktoz (Krema)"
  },
  {
    id: "ispanak-yataginda-tavuk",
    category: "Tavuk Çeşitleri",
    categorySlug: "tavuk",
    name: "Ispanak Yatağında Tavuk Bonfile",
    subtitle: "Kremalı Taze Ispanak • Izgara Tavuk Göğsü",
    price: "₺ 570",
    priceNum: 570,
    image: "/dishes/tavuk-sis.png",
    dishImage: "/dishes/tavuk-sis.png",
    description: "Kremalı sotelenmiş taze ıspanak yatağında ızgara tavuk fileto.",
    chefNote: "Kremalı sotelenmiş taze ıspanak yatağında ızgara tavuk fileto.",
    calories: "490 kcal",
    prepTime: "16 dk",
    servingTemp: "74°C",
    temperature: "74°C",
    portion: "310g",
    allergens: "Laktoz"
  },
  {
    id: "kremali-mantarli-tavuk",
    category: "Tavuk Çeşitleri",
    categorySlug: "tavuk",
    name: "Kremalı Mantarlı Tavuk",
    subtitle: "Taze Kültür Mantarı • Yoğun Krema • Kekik",
    price: "₺ 550",
    priceNum: 550,
    image: "/dishes/kremali-tavuk.png",
    dishImage: "/dishes/kremali-tavuk.png",
    description: "Tereyağında sotelenmiş mantarlar ve nefis krema soslu tavuk lokumları.",
    chefNote: "Tereyağında sotelenmiş mantarlar ve nefis krema soslu tavuk lokumları.",
    calories: "560 kcal",
    prepTime: "15 dk",
    servingTemp: "75°C",
    temperature: "75°C",
    portion: "330g",
    allergens: "Laktoz"
  },
  {
    id: "acili-tavuk",
    category: "Tavuk Çeşitleri",
    categorySlug: "tavuk",
    name: "Beroş Usulü Acılı Tavuk",
    subtitle: "Köz Biber Sosu • Zencefil & Sarımsak Marinesi",
    price: "₺ 540",
    priceNum: 540,
    image: "/dishes/acili-tavuk.png",
    dishImage: "/dishes/acili-tavuk.png",
    description: "Acı biber glazeli wok tavada çevrilmiş çıtır tavuk lokumları.",
    chefNote: "Acı biber glazeli wok tavada çevrilmiş çıtır tavuk lokumları.",
    calories: "520 kcal",
    prepTime: "14 dk",
    servingTemp: "76°C",
    temperature: "76°C",
    portion: "300g",
    allergens: "Alerjensiz"
  },

  // ================= 5. ARA SICAK & ÇORBA & MEZELER (6 Ürün) =================
  {
    id: "mumbar",
    category: "Ara Sıcak & Mezeler",
    categorySlug: "corba-meze",
    name: "Diyarbakır Usulü Mumbar",
    subtitle: "Satır Eti • Baharatlı Pirinç Dolgusu • Haşlama",
    price: "₺ 480",
    priceNum: 480,
    image: "/dishes/mumbar.png",
    dishImage: "/dishes/mumbar.png",
    description: "Titizlikle temizlenip taze baharatlı pirinçle doldurulan Diyarbakır klasiği.",
    chefNote: "Titizlikle temizlenip taze baharatlı pirinçle doldurulan Diyarbakır klasiği.",
    calories: "620 kcal",
    prepTime: "10 dk",
    servingTemp: "78°C",
    temperature: "78°C",
    portion: "250g",
    allergens: "Alerjensiz"
  },
  {
    id: "icli-kofte",
    category: "Ara Sıcak & Mezeler",
    categorySlug: "corba-meze",
    name: "Haşlama İçli Köfte (2 Adet)",
    subtitle: "İncecik Bulgur Zırhı • Cevizli Kuzu Kıyma Harcı",
    price: "₺ 160",
    priceNum: 160,
    image: "/dishes/icli-kofte.png",
    dishImage: "/dishes/icli-kofte.png",
    description: "Geleneksel usulde suda haşlanan, içi sulu kuzu kıymalı ve cevizli köfte.",
    chefNote: "Geleneksel usulde suda haşlanan, içi sulu kuzu kıymalı ve cevizli köfte.",
    calories: "380 kcal",
    prepTime: "8 dk",
    servingTemp: "75°C",
    temperature: "75°C",
    portion: "2 Adet",
    allergens: "Gluten, Kuruyemiş (Ceviz)"
  },
  {
    id: "talas-boregi",
    category: "Ara Sıcak & Mezeler",
    categorySlug: "corba-meze",
    name: "Geleneksel Talaş Böreği",
    subtitle: "Çıtır Milföy Katları • Kuzu Kuşbaşı & Bezelye",
    price: "₺ 220",
    priceNum: 220,
    image: "/dishes/meze-tabagi.png",
    dishImage: "/dishes/meze-tabagi.png",
    description: "Fırından yeni çıkmış çıtır çıtır milföy hamurunda etli börek.",
    chefNote: "Fırından yeni çıkmış çıtır çıtır milföy hamurunda etli börek.",
    calories: "440 kcal",
    prepTime: "10 dk",
    servingTemp: "75°C",
    temperature: "75°C",
    portion: "1 Adet",
    allergens: "Gluten, Laktoz"
  },
  {
    id: "kelle-paca",
    category: "Ara Sıcak & Mezeler",
    categorySlug: "corba-meze",
    name: "Diyarbakır Kelle Paça",
    subtitle: "İlikli Kemik Suyu • Sarımsak & Sirkeli Terbiye",
    price: "₺ 260",
    priceNum: 260,
    image: "/dishes/kelle-paca.png",
    dishImage: "/dishes/kelle-paca.png",
    description: "Odun ateşinde 10 saat demlenen şifa kaynağı orijinal kelle paça.",
    chefNote: "Odun ateşinde 10 saat demlenen şifa kaynağı orijinal kelle paça.",
    calories: "450 kcal",
    prepTime: "5 dk",
    servingTemp: "82°C",
    temperature: "82°C",
    portion: "1 Kase",
    allergens: "Alerjensiz"
  },
  {
    id: "patates-cips",
    category: "Ara Sıcak & Mezeler",
    categorySlug: "corba-meze",
    name: "El Yapımı Patates Cips",
    subtitle: "Taze Patates Dilimleri • Kekikli Deniz Tuzu",
    price: "₺ 220",
    priceNum: 220,
    image: "/dishes/meze-tabagi.png",
    dishImage: "/dishes/meze-tabagi.png",
    description: "İncecik kesilip altın renginde kızartılan el yapımı patatesler.",
    chefNote: "İncecik kesilip altın renginde kızartılan el yapımı patatesler.",
    calories: "380 kcal",
    prepTime: "8 dk",
    servingTemp: "75°C",
    temperature: "75°C",
    portion: "1 Porsiyon",
    allergens: "Alerjensiz"
  },
  {
    id: "sade-pilav",
    category: "Ara Sıcak & Mezeler",
    categorySlug: "corba-meze",
    name: "Sade Pirinç Pilavı",
    subtitle: "Baldo Pirinç • Hakiki Sade Tereyağı",
    price: "₺ 130",
    priceNum: 130,
    image: "/dishes/meze-tabagi.png",
    dishImage: "/dishes/meze-tabagi.png",
    description: "Tane tane dökülen tereyağlı geleneksel pirinç pilavı.",
    chefNote: "Tane tane dökülen tereyağlı geleneksel pirinç pilavı.",
    calories: "310 kcal",
    prepTime: "5 dk",
    servingTemp: "72°C",
    temperature: "72°C",
    portion: "1 Porsiyon",
    allergens: "Laktoz (Tereyağı)"
  },

  // ================= 6. GELENEKSEL TATLILAR (7 Ürün) =================
  {
    id: "fistikli-kadayif",
    category: "Geleneksel Tatlılar",
    categorySlug: "tatlilar",
    name: "Diyarbakır Burma Kadayıf",
    subtitle: "Hakiki Sade Yağ • Bol Boz Antep Fıstığı • Sıcak Şerbet",
    price: "₺ 430",
    priceNum: 430,
    image: "/dishes/fistikli-kadayif.png",
    dishImage: "/dishes/fistikli-kadayif.png",
    description: "Geleneksel ocakta altın renginde kızartılan meşhur çıtır burma kadayıf.",
    chefNote: "Geleneksel ocakta altın renginde kızartılan meşhur çıtır burma kadayıf.",
    calories: "520 kcal",
    prepTime: "5 dk",
    servingTemp: "60°C",
    temperature: "60°C",
    portion: "1 Porsiyon",
    allergens: "Gluten, Kuruyemiş (Fıstık), Laktoz"
  },
  {
    id: "fistikli-baklava",
    category: "Geleneksel Tatlılar",
    categorySlug: "tatlilar",
    name: "Antep Fıstıklı Havuç Dilim Baklava",
    subtitle: "40 Kat İncecik Yufka • Bol Antep Fıstığı",
    price: "₺ 450",
    priceNum: 450,
    image: "/dishes/fistikli-baklava.png",
    dishImage: "/dishes/fistikli-baklava.png",
    description: "Kat kat açılan yufkaların fıstık ve sade yağ ile eşsiz dansı.",
    chefNote: "Kat kat açılan yufkaların fıstık ve sade yağ ile eşsiz dansı.",
    calories: "540 kcal",
    prepTime: "5 dk",
    servingTemp: "Oda Sıcaklığı",
    temperature: "Oda Sıcaklığı",
    portion: "1 Porsiyon",
    allergens: "Gluten, Kuruyemiş (Fıstık), Laktoz"
  },
  {
    id: "kunefe",
    category: "Geleneksel Tatlılar",
    categorySlug: "tatlilar",
    name: "Hatay Usulü Künefe",
    subtitle: "Eriyen Tuzsuz Peynir • Çıtır Tel Kadayıf",
    price: "₺ 380",
    priceNum: 380,
    image: "/dishes/kunefe.png",
    dishImage: "/dishes/kunefe.png",
    description: "Közde bakır tepside çevrilerek pişirilen, uzayan peynirli sıcacık künefe.",
    chefNote: "Közde bakır tepside çevrilerek pişirilen, uzayan peynirli sıcacık künefe.",
    calories: "560 kcal",
    prepTime: "12 dk",
    servingTemp: "70°C",
    temperature: "70°C",
    portion: "1 Porsiyon",
    allergens: "Gluten, Laktoz"
  },
  {
    id: "fistik-sarma",
    category: "Geleneksel Tatlılar",
    categorySlug: "tatlilar",
    name: "Özel Fıstık Sarma",
    subtitle: "Yalnızca Saf Boz Fıstık Ezmesi & Tek Kat Yufka",
    price: "₺ 490",
    priceNum: 490,
    image: "/dishes/fistik-sarma.png",
    dishImage: "/dishes/fistik-sarma.png",
    description: "Yoğun Antep fıstığı dolgusu ile damaklarda iz bırakan lezzet şöleni.",
    chefNote: "Yoğun Antep fıstığı dolgusu ile damaklarda iz bırakan lezzet şöleni.",
    calories: "490 kcal",
    prepTime: "5 dk",
    servingTemp: "Oda Sıcaklığı",
    temperature: "Oda Sıcaklığı",
    portion: "1 Porsiyon",
    allergens: "Gluten, Kuruyemiş (Fıstık)"
  },
  {
    id: "soguk-baklava",
    category: "Geleneksel Tatlılar",
    categorySlug: "tatlilar",
    name: "Sütlü Soğuk Baklava",
    subtitle: "Sütlü Şerbet • Belçika Çikolatası & Bol Fıstık",
    price: "₺ 400",
    priceNum: 400,
    image: "/dishes/soguk-baklava.png",
    dishImage: "/dishes/soguk-baklava.png",
    description: "Hafif süt şerbeti ve kakao tozuyla serinleten modern baklava.",
    chefNote: "Hafif süt şerbeti ve kakao tozuyla serinleten modern baklava.",
    calories: "410 kcal",
    prepTime: "5 dk",
    servingTemp: "4°C Soğuk",
    temperature: "4°C Soğuk",
    portion: "1 Porsiyon",
    allergens: "Gluten, Laktoz, Kuruyemiş"
  },
  {
    id: "kabak-tatlisi",
    category: "Geleneksel Tatlılar",
    categorySlug: "tatlilar",
    name: "Tahinli Cevizli Kabak Tatlısı",
    subtitle: "Fırınlanmış Bal Kabağı • Bozkır Tahini • Dövme Ceviz",
    price: "₺ 250",
    priceNum: 250,
    image: "/dishes/kabak-tatlisi.png",
    dishImage: "/dishes/kabak-tatlisi.png",
    description: "Kendi suyunda karamelize olmuş bal kabağı, tahin ve ceviz eşliğinde.",
    chefNote: "Kendi suyunda karamelize olmuş bal kabağı, tahin ve ceviz eşliğinde.",
    calories: "340 kcal",
    prepTime: "5 dk",
    servingTemp: "Oda Sıcaklığı",
    temperature: "Oda Sıcaklığı",
    portion: "1 Porsiyon",
    allergens: "Susam (Tahin), Kuruyemiş (Ceviz)"
  },
  {
    id: "dondurma-top",
    category: "Geleneksel Tatlılar",
    categorySlug: "tatlilar",
    name: "Maraş Dövme Dondurma (Top)",
    subtitle: "Hakiki Keçi Sütü & Doğal Sahlep",
    price: "₺ 120",
    priceNum: 120,
    image: "/dishes/dondurma-top.png",
    dishImage: "/dishes/dondurma-top.png",
    description: "Tatlıların yanına mükemmel eşlik eden dövme Maraş dondurması.",
    chefNote: "Tatlıların yanına mükemmel eşlik eden dövme Maraş dondurması.",
    calories: "140 kcal",
    prepTime: "3 dk",
    servingTemp: "-12°C",
    temperature: "-12°C",
    portion: "2 Top",
    allergens: "Laktoz"
  },

  // ================= 7. KAHVALTI & SALATALAR (4 Ürün) =================
  {
    id: "serpme-kahvalti",
    category: "Kahvaltı & Salatalar",
    categorySlug: "salata",
    name: "Tarihi Konak Serpme Kahvaltı",
    subtitle: "Yöresel Peynirler • Otlu Peynir • Sıcak Pide & Menemen",
    price: "₺ 650",
    priceNum: 650,
    image: "/dishes/serpme-kahvalti.png",
    dishImage: "/dishes/serpme-kahvalti.png",
    description: "Güneydoğu'nun taze süt ürünleri, bal kaymak ve konak reçeteleriyle donatılmış zengin sofra.",
    chefNote: "Güneydoğu'nun taze süt ürünleri, bal kaymak ve konak reçeteleriyle donatılmış zengin sofra.",
    calories: "950 kcal",
    prepTime: "15 dk",
    servingTemp: "Taze Servis",
    temperature: "Taze Servis",
    portion: "Kişi Başı",
    allergens: "Laktoz, Gluten, Yumurta"
  },
  {
    id: "kahvalti-tabagi",
    category: "Kahvaltı & Salatalar",
    categorySlug: "salata",
    name: "Zengin Kahvaltı Tabağı",
    subtitle: "Örgü Peyniri • Zeytinler • Petek Bal & Tereyağı",
    price: "₺ 350",
    priceNum: 350,
    image: "/dishes/kahvalti-tabagi.png",
    dishImage: "/dishes/kahvalti-tabagi.png",
    description: "Pratik ve doyurucu tek kişilik gurme kahvaltı tabağı.",
    chefNote: "Pratik ve doyurucu tek kişilik gurme kahvaltı tabağı.",
    calories: "580 kcal",
    prepTime: "10 dk",
    servingTemp: "Taze Servis",
    temperature: "Taze Servis",
    portion: "1 Kişilik",
    allergens: "Laktoz, Gluten"
  },
  {
    id: "kasik-salatasi",
    category: "Kahvaltı & Salatalar",
    categorySlug: "salata",
    name: "Yöresel Kaşık Salatası",
    subtitle: "İnce Kıyım Domates & Salatalık • Nar Ekşisi • Sumak",
    price: "₺ 250",
    priceNum: 250,
    image: "/dishes/kasik-salatasi.png",
    dishImage: "/dishes/kasik-salatasi.png",
    description: "Et yemeklerinin vazgeçilmez ferahlatıcı eşlikçisi kaşık salatası.",
    chefNote: "Et yemeklerinin vazgeçilmez ferahlatıcı eşlikçisi kaşık salatası.",
    calories: "180 kcal",
    prepTime: "8 dk",
    servingTemp: "Soğuk",
    temperature: "Soğuk",
    portion: "1 Kase",
    allergens: "Alerjensiz"
  },
  {
    id: "kase-yogurt",
    category: "Kahvaltı & Salatalar",
    categorySlug: "salata",
    name: "Süzme Köy Yoğurdu",
    subtitle: "Doğal Maya • Yoğun Kıvamlı Köy Sütü",
    price: "₺ 220",
    priceNum: 220,
    image: "/dishes/meze-tabagi.png",
    dishImage: "/dishes/meze-tabagi.png",
    description: "Geleneksel çömlek kapta mayalanmış saf köy yoğurdu.",
    chefNote: "Geleneksel çömlek kapta mayalanmış saf köy yoğurdu.",
    calories: "210 kcal",
    prepTime: "3 dk",
    servingTemp: "4°C Soğuk",
    temperature: "4°C Soğuk",
    portion: "1 Kase",
    allergens: "Laktoz"
  },

  // ================= 8. İÇECEKLER & SPESİYALLER (10 Ürün) =================
  {
    id: "acik-ayran",
    category: "İçecekler & Spesiyaller",
    categorySlug: "icecekler",
    name: "Hakiki Yayık Açık Ayran",
    subtitle: "Doğal Köy Yoğurdu • Bakır Maşrapada Bol Köpüklü",
    price: "₺ 75",
    priceNum: 75,
    image: "/dishes/acik-ayran.png",
    dishImage: "/dishes/acik-ayran.png",
    description: "Geleneksel yayıkta çalkalanan buz gibi bol köpüklü ayran.",
    chefNote: "Geleneksel yayıkta çalkalanan buz gibi bol köpüklü ayran.",
    calories: "90 kcal",
    prepTime: "2 dk",
    servingTemp: "4°C Buz Gibi",
    temperature: "4°C Buz Gibi",
    portion: "Bakır Maşrapa",
    allergens: "Laktoz"
  },
  {
    id: "salgam",
    category: "İçecekler & Spesiyaller",
    categorySlug: "icecekler",
    name: "Acılı / Sade Şalgam Suyu",
    subtitle: "Doğal Fermantasyon Mor Havuç • Tane Acılı",
    price: "₺ 75",
    priceNum: 75,
    image: "/dishes/salgam.png",
    dishImage: "/dishes/salgam.png",
    description: "Geleneksel fıçılarda dinlendirilen sindirimi kolaylaştırıcı şalgam.",
    chefNote: "Geleneksel fıçılarda dinlendirilen sindirimi kolaylaştırıcı şalgam.",
    calories: "25 kcal",
    prepTime: "2 dk",
    servingTemp: "Soğuk",
    temperature: "Soğuk",
    portion: "330ml",
    allergens: "Gluten (Eser Miktarda Maya)"
  },
  {
    id: "limonata",
    category: "İçecekler & Spesiyaller",
    categorySlug: "icecekler",
    name: "Ev Yapımı Nane Limonata",
    subtitle: "Sıkma Akdeniz Limonu • Taze Bahçe Nanesi",
    price: "₺ 85",
    priceNum: 85,
    image: "/dishes/limonata.png",
    dishImage: "/dishes/limonata.png",
    description: "Taze nane yaprakları ve limon kabuklarıyla ovulan serinletici lezzet.",
    chefNote: "Taze nane yaprakları ve limon kabuklarıyla ovulan serinletici lezzet.",
    calories: "110 kcal",
    prepTime: "3 dk",
    servingTemp: "Buzlu",
    temperature: "Buzlu",
    portion: "350ml",
    allergens: "Alerjensiz"
  },
  {
    id: "turk-kahvesi",
    category: "İçecekler & Spesiyaller",
    categorySlug: "icecekler",
    name: "Közde Kumda Türk Kahvesi",
    subtitle: "Ağır Ağır Pişen Bol Köpüklü • Damla Sakızlı Lokum",
    price: "₺ 65",
    priceNum: 65,
    image: "/dishes/turk-kahvesi.png",
    dishImage: "/dishes/turk-kahvesi.png",
    description: "Sıcak kum havuzunda bakır cezvede ağır ağır kabartılan konak kahvesi.",
    chefNote: "Sıcak kum havuzunda bakır cezvede ağır ağır kabartılan konak kahvesi.",
    calories: "15 kcal",
    prepTime: "5 dk",
    servingTemp: "85°C Sıcak",
    temperature: "85°C Sıcak",
    portion: "Fincan",
    allergens: "Alerjensiz"
  },
  {
    id: "kutu-kola",
    category: "İçecekler & Spesiyaller",
    categorySlug: "icecekler",
    name: "Kutu Kola (Coca-Cola / Zero)",
    subtitle: "Buz ve Limon Dilimi İle Servis Edilir",
    price: "₺ 80",
    priceNum: 80,
    image: "/dishes/salgam.png",
    dishImage: "/dishes/salgam.png",
    description: "Soğuk kutu meşrubat.",
    chefNote: "Soğuk kutu meşrubat.",
    calories: "140 kcal",
    prepTime: "1 dk",
    servingTemp: "Soğuk",
    temperature: "Soğuk",
    portion: "330ml Kutu",
    allergens: "Alerjensiz"
  },
  {
    id: "kutu-fanta",
    category: "İçecekler & Spesiyaller",
    categorySlug: "icecekler",
    name: "Kutu Fanta",
    subtitle: "Portakal Ferahlığı • Soğuk Servis",
    price: "₺ 80",
    priceNum: 80,
    image: "/dishes/portakal-suyu.png",
    dishImage: "/dishes/portakal-suyu.png",
    description: "Portakal aromalı kutu gazlı içecek.",
    chefNote: "Portakal aromalı kutu gazlı içecek.",
    calories: "130 kcal",
    prepTime: "1 dk",
    servingTemp: "Soğuk",
    temperature: "Soğuk",
    portion: "330ml Kutu",
    allergens: "Alerjensiz"
  },
  {
    id: "sise-kola",
    category: "İçecekler & Spesiyaller",
    categorySlug: "icecekler",
    name: "Cam Şişe Kola",
    subtitle: "Orijinal Cam Şişe • Buz Gibi",
    price: "₺ 80",
    priceNum: 80,
    image: "/dishes/salgam.png",
    dishImage: "/dishes/salgam.png",
    description: "Geleneksel cam şişede sunulan soğuk meşrubat.",
    chefNote: "Geleneksel cam şişede sunulan soğuk meşrubat.",
    calories: "140 kcal",
    prepTime: "1 dk",
    servingTemp: "Soğuk",
    temperature: "Soğuk",
    portion: "250ml Şişe",
    allergens: "Alerjensiz"
  },
  {
    id: "sprite",
    category: "İçecekler & Spesiyaller",
    categorySlug: "icecekler",
    name: "Sprite",
    subtitle: "Limon & Misket Limonu Ferahlığı",
    price: "₺ 80",
    priceNum: 80,
    image: "/dishes/limonata.png",
    dishImage: "/dishes/limonata.png",
    description: "Ferahlatıcı gazlı gazoz.",
    chefNote: "Ferahlatıcı gazlı gazoz.",
    calories: "120 kcal",
    prepTime: "1 dk",
    servingTemp: "Soğuk",
    temperature: "Soğuk",
    portion: "330ml",
    allergens: "Alerjensiz"
  },
  {
    id: "sade-soda",
    category: "İçecekler & Spesiyaller",
    categorySlug: "icecekler",
    name: "Beypazarı Doğal Maden Suyu",
    subtitle: "Zengin Mineralli Doğal Kaynak Suyu",
    price: "₺ 75",
    priceNum: 75,
    image: "/dishes/limonata.png",
    dishImage: "/dishes/limonata.png",
    description: "Yemek sonrası hazmı kolaylaştıran doğal maden suyu.",
    chefNote: "Yemek sonrası hazmı kolaylaştıran doğal maden suyu.",
    calories: "0 kcal",
    prepTime: "1 dk",
    servingTemp: "Soğuk",
    temperature: "Soğuk",
    portion: "200ml Şişe",
    allergens: "Alerjensiz"
  },
  {
    id: "cay",
    category: "İçecekler & Spesiyaller",
    categorySlug: "icecekler",
    name: "Demleme Konak Çayı",
    subtitle: "Kaçak & Rize Harmanı • İnce Belli Bardak",
    price: "₺ 35",
    priceNum: 35,
    image: "/dishes/turk-kahvesi.png",
    dishImage: "/dishes/turk-kahvesi.png",
    description: "Bakır semaverde demlenen taze konak çayı.",
    chefNote: "Bakır semaverde demlenen taze konak çayı.",
    calories: "5 kcal",
    prepTime: "1 dk",
    servingTemp: "85°C Taze Dem",
    temperature: "85°C Taze Dem",
    portion: "İnce Belli Bardak",
    allergens: "Alerjensiz"
  },

  // ================= 9. ÇOCUK MENÜSÜ (2 Ürün) =================
  {
    id: "izgara-kofte",
    category: "Çocuk Menüsü",
    categorySlug: "tas-firin",
    name: "Izgara Anne Köftesi Menü",
    subtitle: "Patates Kızartması & Pirinç Pilavı Eşliğinde",
    price: "₺ 550",
    priceNum: 550,
    image: "/dishes/karisik-izgara.png",
    dishImage: "/dishes/karisik-izgara.png",
    description: "Az baharatlı dana kıymasından yumuşak ızgara köfteler.",
    chefNote: "Az baharatlı dana kıymasından yumuşak ızgara köfteler.",
    calories: "520 kcal",
    prepTime: "12 dk",
    servingTemp: "75°C",
    temperature: "75°C",
    portion: "1 Menü",
    allergens: "Gluten"
  },
  {
    id: "tavuk-nugget",
    category: "Çocuk Menüsü",
    categorySlug: "tavuk",
    name: "Çıtır Tavuk Nugget Menü",
    subtitle: "Parmak Patates & Ketçap-Mayonez İle",
    price: "₺ 510",
    priceNum: 510,
    image: "/dishes/tavuk-sis.png",
    dishImage: "/dishes/tavuk-sis.png",
    description: "Tavuk göğsünden taze hazırlanan altın rengi çıtır nugget'lar.",
    chefNote: "Tavuk göğsünden taze hazırlanan altın rengi çıtır nugget'lar.",
    calories: "480 kcal",
    prepTime: "10 dk",
    servingTemp: "74°C",
    temperature: "74°C",
    portion: "1 Menü",
    allergens: "Gluten, Yumurta"
  }
];

console.log("Catalog total items:", catalog.length);

// Verify all dish images
let missingImages = 0;
for (const d of catalog) {
  const imgPath = path.join(process.cwd(), "public", d.image.replace(/^\//, ""));
  if (!fs.existsSync(imgPath)) {
    console.warn("MISSING:", d.id, "->", d.image);
    missingImages++;
  }
}
console.log("Missing images count:", missingImages);

fs.writeFileSync("scratch/prepared_63_dishes.json", JSON.stringify(catalog, null, 2));
console.log("Saved scratch/prepared_63_dishes.json");
